-- Schema for the favorites feature (FavoritesScreen / FavoritesDatabaseService).
--
-- Run this once in the Supabase SQL editor for this project. It can't be
-- applied automatically from the app — creating tables/policies requires
-- more than the anon/publishable key the Flutter app uses.
--
-- Both tables are scoped to auth.uid(), so favorites only work for a
-- signed-in user (Supabase Auth sign up / sign in in create_acount_screen.dart) —
-- not for the "تخطي الآن" skip flow, which never authenticates.

create table if not exists public.favorite_providers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  -- Full snapshot of the Providers row at save time (Providers.toJson()),
  -- including its original `id` — kept independent of the live `providers`
  -- table so a favorite still displays correctly even if that row later
  -- changes or is removed.
  provider jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.favorite_providers enable row level security;

create policy "Users can view their own favorite providers"
  on public.favorite_providers for select
  using (auth.uid() = user_id);

create policy "Users can insert their own favorite providers"
  on public.favorite_providers for insert
  with check (auth.uid() = user_id);

create policy "Users can delete their own favorite providers"
  on public.favorite_providers for delete
  using (auth.uid() = user_id);

create table if not exists public.favorite_plans (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  -- OnboardingAnswers.eventType (the event_type question's Arabic option
  -- title, e.g. "زفاف") — doubles as the plan's display name since there's
  -- no separate "name your event" field yet.
  event_type text not null,
  guest_count integer not null,
  budget numeric not null,
  -- Every recommended provider actually shown at save time (one per
  -- selected needs-category, post any "البديل" swaps), each a full
  -- Providers.toJson() snapshot — same reasoning as favorite_providers.provider.
  providers jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.favorite_plans enable row level security;

create policy "Users can view their own favorite plans"
  on public.favorite_plans for select
  using (auth.uid() = user_id);

create policy "Users can insert their own favorite plans"
  on public.favorite_plans for insert
  with check (auth.uid() = user_id);

create policy "Users can delete their own favorite plans"
  on public.favorite_plans for delete
  using (auth.uid() = user_id);
